stages:
  - build
  - deploy

build:
  stage: build
  image: node:22.12.0
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
  only:
    - main

deploy:
  stage: deploy
  image: node:22.12.0
  script:
    - npm install -g vercel
    - vercel --token $VERCEL_TOKEN --prod --yes
  only:
    - main
